routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | This file is where you may define all of the routes that are handled
  | by your application. Just tell Laravel the URIs it should respond
  | to using a Closure or controller method. Build something great!
  |
 */

Route::get('/', function () {
    //return view('welcome');
    return redirect('login/');
});

Auth::routes();

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'middleware' => ['auth']
        ], function() {

    Route::get('/home', 'HomeController@index');
    
    Route::get('/users/destroy/{id}', ['as' => 'users.destroy', 'uses' => 'UserController@destroy']);
    Route::resource('users', 'UserController', [
        'only' => [
            'index', 'create', 'store', 'update', 'edit'//, 'destroy'
        ]
    ]);

    Route::get('/rooms/destroy/{id}', ['as' => 'rooms.destroy', 'uses' => 'RoomsController@destroy']);
    Route::resource('rooms', 'RoomsController', [
        'only' => [
            'index', 'create', 'store', 'update', 'edit'//, 'destroy'
        ]
    ]);
    
    Route::get('/room-reservations/destroy/{id}', ['as' => 'room-reservations.destroy', 'uses' => 'RoomReservationsController@destroy']);
    Route::resource('room-reservations', 'RoomReservationsController', [
        'only' => [
            'index', 'create', 'store', 'update', 'edit'//, 'destroy'
        ]
    ]);
});

app/Models/RoomReservation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RoomReservation extends Model {

    protected $fillable = [
        'room_id',
        'user_id',
        'date_reservation',
        'start_period',
        'finish_period'
    ];

    public function room() {
        return $this->belongsTo('App\Models\Room', 'room_id', 'id');
    }

    public function user() {
        return $this->belongsTo('App\User', 'user_id', 'id');
    }
}

app/Http/Controllers/RoomReservationsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\RoomReservationsRequest;
use App\Models\RoomReservation;
use App\Models\Room;
use Auth;

class RoomReservationsController extends Controller {

    private $roomReservation;
    private $room;

    public function __construct(RoomReservation $roomReservation, Room $room) {

        $this->roomReservation = $roomReservation;
        $this->room = $room;
    }

    public function index() {

        $roomReservations = $this->roomReservation->with('room', 'user')->paginate(7);

        return view('admin.room-reservation.index', compact('roomReservations'));
    }

    public function store(RoomReservationsRequest $request) {

        $input = $request->all();
        $input['user_id'] = Auth::user()->id;
        $input['finish_period'] = $input['start_period'] + 1;

        $checkByUserAndPeriod = $this->roomReservation
                ->where('user_id', $input['user_id'])
                ->where('room_id', $input['room_id'])
                ->where('date_reservation', $input['date_reservation'])
                ->where('start_period', $input['start_period'])
                ->where('finish_period', $input['finish_period'])
                ->count();

        $checkByOtherUserAndPeriod = $this->roomReservation
                ->where('user_id', '!=', $input['user_id'])
                ->where('room_id', $input['room_id'])
                ->where('date_reservation', $input['date_reservation'])
                ->where('start_period', $input['start_period'])
                ->where('finish_period', $input['finish_period'])
                ->count();

        if ($checkByUserAndPeriod != 0) {
            $request->session()->flash('warning', 'Sala reservada nesse horário.');
            return redirect()->back();
        }
        if ($checkByOtherUserAndPeriod != 0) {
            $request->session()->flash('warning', 'Sala reservada nesse por outra pessoa nesse horário.');
            return redirect()->back();
        }

        RoomReservation::create($input);
        return redirect('admin/room-reservations');
    }

    public function create() {

        $roomReservation = new Room();
        $rooms = $this->room->get()->pluck('title', 'id');
        //dd($rooms);

        return view('admin.room-reservation.create', compact('roomReservation', 'rooms'));
    }

    public function destroy($id, Request $request) {


        $roomReservation = $this->roomReservation->find($id)->delete();

        $request->session()->flash('success', 'Reserva Cancalada.');
        return redirect()->back();
    }

}

resources/views/admin/room-reservation/_form.blade.php
@include('errors._error_field')

<?php $errorClass = $errors->first('name') ? ['class' => 'validate invalid'] : []; ?>

    @include('shared.message')
<div class="row">
      <div class="col-md-3">
           <div class="form-group">
      
            {!! Form::label('room_id', 'Sala') !!}
            {!! Form::select('room_id', $rooms, $roomReservation->room_id,  array_merge(['class' => 'form-control', 'required' =>'required'])) !!}
        </div>
    </div>
    <div class="col-sm-2">
     <div class="form-group">
    
       
            {!! Form::label('date_reservation', 'Data de reserva', ['data-error' => $errors->first('date_reservation')]) !!}
            {!! Form::text('date_reservation', 
            empty($roomReservation->date_reservation)? '' : Carbon\Carbon::parse($roomReservation->date_reservation)->format('d-m-Y ')
            , array_merge(['class' => 'form-control datetimepicker date'], $errorClass)) !!}
        </div>
    </div>
      <div class="col-md-3">
    <div class="form-group">
      
            {!! Form::label('start_period', 'Periodo de uma horas') !!}
            {!! Form::select('start_period', [''=>'Selecione',
            '8'=>'8 horas','9'=>'9 horas','10'=>'10 horas','11'=>'11 horas','12'=>'12 horas','13'=>'13 horas',
            '14'=>'14 horas','15'=>'15 horas','16'=>'16 horas','17'=>'17 horas','18'=>'18 horas'], null,  array_merge(['class' => 'form-control', 'required' =>'required'])) !!}
        </div>
    </div>

</div>


<div class="row">

    <div class="col-sm-12">
        <br/>
        {!! Form::submit($btnSubmitName, ['class' => 'btn btn-primary btn-lg waves-effect right']) !!}
        <a href="{{ route('admin.room-reservations.index')}}" class="btn btn-danger btn-lg waves-effect right">Cancelar</a>
    </div>
</div><!-- row -->

resources/views/admin/room-reservation/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.room-reservations.index')}}">Reservas</a></li>
        <li class="active"><a href="#">Cadastro</a></li>

    </ol>
    <div class="row">
        <div class="col-md-12 ">
            <div class="panel panel-default">
                <div  style="padding: 15px">

                    <h3>Reservas</h3>

                    {!! Form::open(['route' => 'admin.room-reservations.store', 'method' => 'post']) !!}

                    @include('admin.room-reservation._form',['btnSubmitName' => 'Salvar'])

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

</div><!-- container -->
@endsection

resources/views/admin/room-reservation/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">




    <div class="row">
        <div class="col-sm-10">
            <h1>Todas Reservas</h1>
        </div>
        <div class="col-sm-2">
            <a href="{{ route('admin.room-reservations.create')}}" class="btn btn-primary pull-right">
                <i class="fa fa-plus" aria-hidden="true"></i> Novo</a>
        </div>
    </div>

    @include('shared.message')

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><h4>Listagem</h4></div>
        <div class="panel-body">
            <!-- Table -->
            <table class="table table-striped">
                <thead style="font-weight: bold; background: #dedede">
                    <tr>
                        <td>Id</td>
                        <td>Sala</td>
                               <td>Período ocupada</td>
                        <td>Usuário</td>
                        <td>Data de reserva</td>
                 
                        <td width="1%" nowrap>Ação</td>
                    </tr>
                </thead>

                @foreach($roomReservations as $val)
                <tbody>
                    <tr>
                        <td>{{ $val->id }}</td>
                        <td>{{ $val->room->title }}</td>
                        <td>{{ $val->start_period }} horas - {{ $val->finish_period }} horas</td>
                        <td>{{ $val->user->name }}</td>
                        <td>{{ Carbon\Carbon::parse($val->date_reservation)->format('d-m-Y ') }}</td>
                        
                        <td width="1%" nowrap>
                            @if( $val->user->id == Auth::user()->id)
                              <a href="{{ route('admin.room-reservations.destroy',['id' => $val->id]) }}" class="btn btn-danger btn-sm ">
                                <i class="fa fa-trash" aria-hidden="true"></i> Cancelar reserva</a>
                            @endif
                          
                        </td>
                    </tr>
                </tbody>
                @endforeach

            </table>
            {!! $roomReservations->render() !!}
        </div>
    </div>
</div>

@include('shared.modal-delete', ['modalId' => 'modalDelete'])

@endsection