routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | This file is where you may define all of the routes that are handled
  | by your application. Just tell Laravel the URIs it should respond
  | to using a Closure or controller method. Build something great!
  |
 */

Route::get('/', function () {
    //return view('welcome');
    return redirect('login/');
});

Auth::routes();

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'middleware' => ['auth']
        ], function() {

    Route::get('/home', 'HomeController@index');
    
    Route::get('/users/destroy/{id}', ['as' => 'users.destroy', 'uses' => 'UserController@destroy']);
    Route::resource('users', 'UserController', [
        'only' => [
            'index', 'create', 'store', 'update', 'edit'//, 'destroy'
        ]
    ]);

    Route::get('/rooms/destroy/{id}', ['as' => 'rooms.destroy', 'uses' => 'RoomsController@destroy']);
    Route::resource('rooms', 'RoomsController', [
        'only' => [
            'index', 'create', 'store', 'update', 'edit'//, 'destroy'
        ]
    ]);
    
    Route::get('/room-reservations/destroy/{id}', ['as' => 'room-reservations.destroy', 'uses' => 'RoomReservationsController@destroy']);
    Route::resource('room-reservations', 'RoomReservationsController', [
        'only' => [
            'index', 'create', 'store', 'update', 'edit'//, 'destroy'
        ]
    ]);
});

app/Models/Room.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class Room extends Model {

    protected $fillable = [
        'cod',
        'title'
    ];
    

    
      
   

}

app/Http/Controllers/RoomsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Room;
use App\Models\RoomReservation;

class RoomsController extends Controller {

    private $room;
    private $roomReservation;

    public function __construct(Room $room, RoomReservation $roomReservation) {
        $this->room = $room;
        $this->roomReservation = $roomReservation;
    }

    public function index() {

        $rooms = $this->room->paginate(5);

        return view('admin.room.index', compact('rooms'));
    }

    public function store(Request $request) {

        $input = $request->all();

        Room::create($input);
        return redirect('admin/rooms');
    }

    public function create() {

        $room = new Room();

        return view('admin.room.create', compact('room'));
    }

    public function edit($id) {
        $room = $this->room->find($id);

        return view('admin.room.edit', compact('room'));
    }

    public function update($id, Request $request) {

        $room = $this->room->find($id);

        $inputs = $request->all();

        $room->update($inputs);
        $request->session()->flash('success', 'Alterado com sucesso.');

        return redirect('admin/rooms');
    }

    public function destroy($id, Request $request) {

        $roomReservations = $this->roomReservation->where('user_id', $id)->count();

        if ($roomReservations != 0) {
            $request->session()->flash('danger', 'Não é possivel excluir, existem registros associados a essa sala.');
            return redirect()->back();
        } else {
            $room = $this->room->find($id)->delete();

            $request->session()->flash('success', 'Excluido com sucesso.');
            return redirect()->back();
        }
    }

}

resources/views/admin/room/_form.blade.php
@include('errors._error_field')

<?php $errorClass = $errors->first('name') ? ['class' => 'validate invalid'] : []; ?>

<div class="row">
    <div class="col-sm-2">
          {!! Form::label('cod', 'Código') !!}
            {!! Form::text('cod', $room->cod, array_merge(['class' => 'form-control input-sm', 'required' => 'required'])) !!}
    </div>
    <div class="col-sm-6">
        <div class="form-group">
            {!! Form::label('title', 'Nome') !!}
            {!! Form::text('title', $room->title, array_merge(['class' => 'form-control  input-sm', 'required' => 'required'])) !!}
        </div>
    </div>
   
      </div>


<div class="row">

    <div class="col-sm-12">
        <br/>
        {!! Form::submit($btnSubmitName, ['class' => 'btn btn-primary btn-lg waves-effect right']) !!}
        <a href="{{ route('admin.rooms.index')}}" class="btn btn-danger btn-lg waves-effect right">Cancelar</a>
    </div>
</div><!-- row -->

resources/views/admin/room/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.rooms.index')}}">Salas</a></li>
        <li class="active"><a href="#">Cadastro</a></li>

    </ol>
    <div class="row">
        <div class="col-md-12 ">
            <div class="panel panel-default">
                <div  style="padding: 15px">

                    <h3>Cadastro de salas</h3>

                    {!! Form::open(['route' => 'admin.rooms.store', 'method' => 'post']) !!}

                    @include('admin.room._form',['btnSubmitName' => 'Salvar'])

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

</div><!-- container -->
@endsection

resources/views/admin/room/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.rooms.index')}}">Produtos</a></li>
        <li class="active"><a href="#">Edição</a></li>

    </ol>
    <div class="row">
        <div class="col-md-12 ">
            <div class="panel panel-default">
                <div  style="padding: 15px">

                    <h3>Editar sala</h3>


                    {!! Form::model($room, ['route' => ['admin.rooms.update',$room->id] ,'method' => 'put']) !!}


                    @include('admin.room._form',['btnSubmitName' => 'Salvar'])

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</div><!-- container -->
@endsection

resources/views/admin/room/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">




    <div class="row">
        <div class="col-sm-10">
            <h1>Salas</h1>
        </div>
        <div class="col-sm-2">
            <a href="{{ route('admin.rooms.create')}}" class="btn btn-primary pull-right">
                <i class="fa fa-plus" aria-hidden="true"></i> Novo</a>
        </div>
    </div>

    @include('shared.message')

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><h4>Listagem</h4></div>
        <div class="panel-body">
            <!-- Table -->
            <table class="table table-striped">
                <thead style="font-weight: bold; background: #dedede">
                    <tr>
                        <td>COD</td>
                        <td>Título</td>
                        <td width="1%" nowrap>Ação</td>
                    </tr>
                </thead>

                @foreach($rooms as $val)
                <tbody>
                    <tr>
                        <td>{{ $val->cod }}</td>
                        <td>{{ $val->title }}</td>
                        <td width="1%" nowrap>
                            <a href="{{ route('admin.rooms.edit', ['id' => $val->id] )}}" class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                            <a href="{{ route('admin.rooms.destroy',['id' => $val->id]) }}" class="btn btn-danger btn-sm "><i class="fa fa-trash" aria-hidden="true"></i></a>
                        </td>
                    </tr>
                </tbody>
                @endforeach

            </table>
            {!! $rooms->render() !!}
        </div>
    </div>
</div>

@include('shared.modal-delete', ['modalId' => 'modalDelete'])

@endsection