routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | This file is where you may define all of the routes that are handled
  | by your application. Just tell Laravel the URIs it should respond
  | to using a Closure or controller method. Build something great!
  |
 */

Route::get('/', function () {
    //return view('welcome');
    return redirect('login/');
});

Auth::routes();

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'middleware' => ['auth']
        ], function() {

    Route::get('/home', 'HomeController@index');
    
    Route::get('/users/destroy/{id}', ['as' => 'users.destroy', 'uses' => 'UserController@destroy']);
    Route::resource('users', 'UserController', [
        'only' => [
            'index', 'create', 'store', 'update', 'edit'//, 'destroy'
        ]
    ]);

    Route::get('/rooms/destroy/{id}', ['as' => 'rooms.destroy', 'uses' => 'RoomsController@destroy']);
    Route::resource('rooms', 'RoomsController', [
        'only' => [
            'index', 'create', 'store', 'update', 'edit'//, 'destroy'
        ]
    ]);
    
    Route::get('/room-reservations/destroy/{id}', ['as' => 'room-reservations.destroy', 'uses' => 'RoomReservationsController@destroy']);
    Route::resource('room-reservations', 'RoomReservationsController', [
        'only' => [
            'index', 'create', 'store', 'update', 'edit'//, 'destroy'
        ]
    ]);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Models\RoomReservation;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller {

    private $users;
    private $roomReservation;

    public function __construct(User $users, RoomReservation $roomReservation) {
        $this->users = $users;
        $this->roomReservation = $roomReservation;
    }

    public function index() {

        $users = $this->users->paginate(5);

        return view('admin.user.index', compact('users'));
    }

    protected function userExist(Request $request) {

        $this->users
                ->where('email', $request['email'])
                ->first();

        if ($this->users->where('email', $request['email'])
                        ->first() != null) {
            return true;
        }

        return false;
    }

    public function create() {
        $users = new User();

        return view('admin.user.create', compact('users'));
    }

    public function store(Request $request) {
        $v = Validator::make($request->all(), [
                    'password' => 'required|min:5',
                    'confirmPassword' => 'required|same:password'
                        ], [], [
                    'password' => 'Senha',
                    'confirmPassword' => 'Confirmação de senha',
        ]);

        if ($v->fails()) {

            return redirect()->back()->withErrors($v);
        }

        $this->userExist($request);

        if ($this->userExist($request) == true) {

            return redirect()->back()->withErrors(
                            $request->session()->flash('success', 'Usuário já cadastrado! Acesse edição de usuários')
            );
        }

        User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => bcrypt($request['password']),
        ]);


        return redirect('admin/users');
    }

    public function edit($id) {
        $users = $this->users->find($id);
        return view('admin.user.edit', compact('users'));
    }

    public function update($id, Request $request) {

        $inputs = $request->all();

        $user = $this->users->find($id);

        if (empty($inputs['password']))
            unset($inputs['password']);
        else
            $inputs['password'] = bcrypt($inputs['password']);

        $user->update($inputs);


        return redirect('admin/users');
    }

    public function destroy($id, Request $request) {

        $roomReservations = $this->roomReservation->where('user_id', $id)->count();

        if ($roomReservations != 0) {
            $request->session()->flash('danger', 'Não é possivel excluir, existem registros associados a essa pessoa.');
            return redirect()->back();
        } else {
            $users = $this->users->find($id)->delete();
            $request->session()->flash('success', 'Excluido com sucesso.');
            return redirect()->back();
            //return ['ok' => true];
        }
    }

}

resources/views/admin/user/_form.blade.php
@if (Session::has('success'))
<div class="alert alert-success">
    <strong>{{ Session::get('success') }}</strong>
</div>


@endif


@if ($errors->has('confirmPassword'))
<div class="alert alert-success">
    <strong>{{ $errors->first('confirmPassword') }}</strong>
</div>
@endif

@if ($errors->has('password'))
<div class="alert alert-success">
    <strong>{{ $errors->first('password') }}</strong>
</div>
@endif
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            {{ csrf_field() }}


            {!! Form::label('name', 'Nome') !!}
            {!! Form::text('name', $users->name, array_merge(['class' => 'form-control', 'required' => 'required'])) !!}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            {!! Form::label('email', 'E-mail') !!}
            {!! Form::text('email', $users->email, array_merge(['class' => 'form-control', 'required' => 'required'])) !!}
        </div>
    </div>

</div>


<div class="row" >
    <div class="col-sm-6">
        @if(!empty($users->id))   
        <label class="checkbox-inline">
            {!! Form::checkbox('alterPass', '' , false, ['id' => 'alterPass']) !!} Alterar senha
        </label>
        @endif

        <div style="{!! (!empty($users->id)) ? 'display:none' : '' !!}"  id="pass">


            {!! Form::label('password', 'Senha', ['data-error' => $errors->first('password')]) !!}
            <input type="password" {!! (empty($users->id)) ? 'required' : '' !!}
            pattern="(?=.*\d)(?=.*[a-z]).{5,}" placeholder="Deve conter mais de 5 caracteres e um número"
            title="Senha deve conter mais de cinco caracteres e um número " size="20" 
            name="password"  class="form-control" onchange="confirmPassword.pattern = this.value;" id="password">

            {!! Form::label('confirmPassword', 'Confirme a senha', ['data-error' => $errors->first('password')]) !!}
            <input type="password" {!! (empty($users->id)) ? 'required' : '' !!} pattern="(?=.*\d)(?=.*[a-z]).{5,}"  class="form-control" 
            title="Senhas diferentes" size="20" placeholder="Repita senha" name="confirmPassword" id="confirmPassword">
        </div>
    </div>
</div>



<!-- row -->

<div class="row">

    <div class="col-sm-12">
        <br/>
        {!! Form::submit($btnSubmitName, ['class' => 'btn btn-primary btn-lg waves-effect right']) !!}

        <a href="{{ route('admin.users.index')}}" class="btn btn-danger btn-lg waves-effect right">Cancelar</a>
    </div>
</div><!-- row -->


@section('javascript-footer')
<script type="text/javascript">
    $(document).ready(function () {
        $('#alterPass').click(function () {
            var elPassword = $("#password"),
                    elConfirmPassword = $("#confirmPassword"),
                    elPass = $("#pass");

            if ($(this).is(':checked') == true) {
                elPass.show();

                elConfirmPassword.prop('required', true);
                elPassword.prop('required', true);
            } else {
                elPassword.prop('required', false).val("");
                elConfirmPassword.prop('required', false).val("");
                elPass.hide();
            }
        });

    });
</script>
@parent
@endsection

resources/views/admin/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<ol class="breadcrumb">
  <li><a href="{{ route('admin.users.index')}}">Usuários</a></li>
  <li class="active"><a href="#">Cadastro</a></li>
  
</ol>
    

        <h3>Cadastro de Usuários</h3>
        <hr/>
<div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                 <div class="panel-body">
        {!! Form::open(['route' => 'admin.users.store', 'method' => 'post']) !!}


            @include('admin.user._form',['btnSubmitName' => 'Salvar'])

        {!! Form::close() !!}
            </div>        </div>
</div>
    
</div><!-- container -->
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.users.index')}}">Usuários</a></li>
        <li class="active"><a href="#">Edição</a></li>

    </ol>


    <h3>Editar usuário</h3>
    <hr/>
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-body">
                {!! Form::model($users, ['route' => ['admin.users.update',$users->id] ,'method' => 'put']) !!}


                @include('admin.user._form',['btnSubmitName' => 'Salvar'])

                {!! Form::close() !!}

            </div></div></div>   
</div><!-- container -->
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">


    

    <div class="row">
        <div class="col-sm-10">
            <h1>Usuários</h1>
        </div>
        <div class="col-sm-2">
            <a href="{{ route('admin.users.create')}}" class="btn btn-primary pull-right"><i class="fa fa-plus" aria-hidden="true"></i> Novo</a>
        </div>
    </div>



    <hr>

    @include('shared.message')

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><h4>Listagem</h4></div>
        <div class="panel-body">

            <p>
                Usuários do sistema
            </p>




            <!-- Table -->
            <table class="table table-striped">
                <thead style="font-weight: bold; background: #dedede">
                    <tr>
                        <td>ID</td>
                        <td>Nome</td>

                        <td>E-mail</td>
                        <td width="1%" nowrap>Ação</td>
                    </tr>
                </thead>

                @foreach($users as $val)
                <tbody>
                    <tr>
                        <td>{{ $val->id }}</td>
                        <td>{{ $val->name }}</td>
                        <td>{{ $val->email }}</td>
                        <td width="1%" nowrap>
                            <a href="{{ route('admin.users.edit',['id' => $val->id]) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                            <a href="{{ route('admin.users.destroy',['id' => $val->id]) }}" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i></a>

                        </td>
                    </tr>
                </tbody>
                @endforeach

            </table>
            {!! $users->render() !!}
        </div></div>
</div>


@include('shared.modal-delete', ['modalId' => 'modalDelete'])

@endsection